//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataweb.NShape.Designer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dataweb.NShape.Designer.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        internal static string ActionCurrConsumption {
            get {
                return ResourceManager.GetString("ActionCurrConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        internal static string ActionCurrGeneration {
            get {
                return ResourceManager.GetString("ActionCurrGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation.
        /// </summary>
        internal static string ActionCurrTransformation {
            get {
                return ResourceManager.GetString("ActionCurrTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        internal static string ActionCurrTransmission {
            get {
                return ResourceManager.GetString("ActionCurrTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        internal static string ActionForeConsumption {
            get {
                return ResourceManager.GetString("ActionForeConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        internal static string ActionForeGeneration {
            get {
                return ResourceManager.GetString("ActionForeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation.
        /// </summary>
        internal static string ActionForeTransformation {
            get {
                return ResourceManager.GetString("ActionForeTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        internal static string ActionForeTransmission {
            get {
                return ResourceManager.GetString("ActionForeTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current operations.
        /// </summary>
        internal static string ActionsCurr {
            get {
                return ResourceManager.GetString("ActionsCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast operations.
        /// </summary>
        internal static string ActionsFore {
            get {
                return ResourceManager.GetString("ActionsFore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphite Editor.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control object state {0}.
        /// </summary>
        internal static string DefaultDiagramNameFmt {
            get {
                return ResourceManager.GetString("DefaultDiagramNameFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to Front.
        /// </summary>
        internal static string MenuBringToFrontTitle {
            get {
                return ResourceManager.GetString("MenuBringToFrontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as Image.
        /// </summary>
        internal static string MenuCopyAsImageTitle {
            get {
                return ResourceManager.GetString("MenuCopyAsImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string MenuCopyTitle {
            get {
                return ResourceManager.GetString("MenuCopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string MenuCutTitle {
            get {
                return ResourceManager.GetString("MenuCutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MenuDeleteTitle {
            get {
                return ResourceManager.GetString("MenuDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shapes selected.
        /// </summary>
        internal static string MenuDescription0 {
            get {
                return ResourceManager.GetString("MenuDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one shape selected.
        /// </summary>
        internal static string MenuDescription1 {
            get {
                return ResourceManager.GetString("MenuDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough shapes selected.
        /// </summary>
        internal static string MenuGroupShapesDescription0 {
            get {
                return ResourceManager.GetString("MenuGroupShapesDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish a role visual relationship between.
        /// </summary>
        internal static string MenuGroupShapesDescription1 {
            get {
                return ResourceManager.GetString("MenuGroupShapesDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objects.
        /// </summary>
        internal static string MenuGroupShapesDescription2 {
            get {
                return ResourceManager.GetString("MenuGroupShapesDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish a role visual relationship.
        /// </summary>
        internal static string MenuGroupShapesTitle {
            get {
                return ResourceManager.GetString("MenuGroupShapesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shapes cut/copied yet.
        /// </summary>
        internal static string MenuPasteDescription {
            get {
                return ResourceManager.GetString("MenuPasteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string MenuPasteTitle {
            get {
                return ResourceManager.GetString("MenuPasteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No redo commands left.
        /// </summary>
        internal static string MenuRedoDescription {
            get {
                return ResourceManager.GetString("MenuRedoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string MenuRedoTitle {
            get {
                return ResourceManager.GetString("MenuRedoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Back.
        /// </summary>
        internal static string MenuSendToBackTitle {
            get {
                return ResourceManager.GetString("MenuSendToBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object information.
        /// </summary>
        internal static string MenuShapeInfoTitle {
            get {
                return ResourceManager.GetString("MenuShapeInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No undo commands left.
        /// </summary>
        internal static string MenuUndoDescription {
            get {
                return ResourceManager.GetString("MenuUndoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string MenuUndoTitle {
            get {
                return ResourceManager.GetString("MenuUndoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role visual relationship selected.
        /// </summary>
        internal static string MenuUngroupShapesDescription0 {
            get {
                return ResourceManager.GetString("MenuUngroupShapesDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break the role visual relationship between.
        /// </summary>
        internal static string MenuUngroupShapesDescription1 {
            get {
                return ResourceManager.GetString("MenuUngroupShapesDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objects.
        /// </summary>
        internal static string MenuUngroupShapesDescription2 {
            get {
                return ResourceManager.GetString("MenuUngroupShapesDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break the role visual relationship.
        /// </summary>
        internal static string MenuUngroupShapesTitle {
            get {
                return ResourceManager.GetString("MenuUngroupShapesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        internal static string NewProjectName {
            get {
                return ResourceManager.GetString("NewProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        internal static string ObjectDiagram {
            get {
                return ResourceManager.GetString("ObjectDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string ObjectProperties {
            get {
                return ResourceManager.GetString("ObjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role visual relationship.
        /// </summary>
        internal static string ObjectRVR {
            get {
                return ResourceManager.GetString("ObjectRVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current o-situation.
        /// </summary>
        internal static string SituationCurr {
            get {
                return ResourceManager.GetString("SituationCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O-situation forecast.
        /// </summary>
        internal static string SituationFore {
            get {
                return ResourceManager.GetString("SituationFore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current state.
        /// </summary>
        internal static string StateCurr {
            get {
                return ResourceManager.GetString("StateCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State forecast.
        /// </summary>
        internal static string StateFore {
            get {
                return ResourceManager.GetString("StateFore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  repair.
        /// </summary>
        internal static string SuffixRepair {
            get {
                return ResourceManager.GetString("SuffixRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current weather.
        /// </summary>
        internal static string WeatherCurr {
            get {
                return ResourceManager.GetString("WeatherCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        internal static string WeatherFore {
            get {
                return ResourceManager.GetString("WeatherFore", resourceCulture);
            }
        }
    }
}
